name: spark_server
version: 0.0.1
author: Alexander Ewetumo <trinoxf@gmail.com>
description: server components for sparkflow
homepage: http://github.com/influx6/spark_server
dependencies:
  hub: any
  bass: any
  rio: any
  sparkflow: any
  spark_utils: any
  spark_fs: any
  guardedfs: any
