name: spark_server
version: 0.0.1
author: Alexander Ewetumo <trinoxf@gmail.com>
description: server components for sparkflow
dependencies:
  hub: any
  bass: any
  rio: any
  sparkflow: any
  spark_utils: any
  spark_fs: any
  guardedfs: any
dependency_overrides:
  guardedfs:
    path: ../guardedfs
  rio:
     path: ../rio
  spark_fs:
     path: ../spark_fs
  sparkflow:
     path: ../sparkflow
  hub:
     path: ../hub
  bass:
     path: ../bass
  spark_utils:
     path: ../spark_utils
